# Generated by Django 6.0.3 on 2026-03-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
