# Generated by Django 6.0.1 on 2026-02-22 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Идентификатор цены в Stripe, создается автоматически', max_length=100, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Идентификатор продукта в Stripe, создается автоматически', max_length=100, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращен'), ('cancelled', 'Отменен')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('one_time', 'Разовый платеж'), ('subscription', 'Подписка')], default='one_time', max_length=20, verbose_name='Тип платежа')),
                ('stripe_session_id', models.CharField(db_index=True, help_text='Идентификатор сессии checkout в Stripe', max_length=255, unique=True, verbose_name='ID сессии Stripe')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, help_text='Идентификатор платежного намерения в Stripe', max_length=255, null=True, verbose_name='ID Payment Intent')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Идентификатор клиента в Stripe (если есть)', max_length=255, null=True, verbose_name='ID клиента Stripe')),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Идентификатор инвойса в Stripe (для подписок)', max_length=255, null=True, verbose_name='ID инвойса Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Идентификатор подписки в Stripe', max_length=255, null=True, verbose_name='ID подписки Stripe')),
                ('payment_method', models.CharField(blank=True, help_text='Например: card, apple_pay, google_pay', max_length=50, null=True, verbose_name='Метод оплаты')),
                ('last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты')),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='materials.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ активен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='materials.course', verbose_name='Курс')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='materials.payment', verbose_name='Платеж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='materials_p_status_922bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='materials_p_user_id_0a932e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseaccess',
            index=models.Index(fields=['user', 'is_active'], name='materials_u_user_id_be3a28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseaccess',
            unique_together={('user', 'course')},
        ),
    ]
